### ISSUE TITLE
Información adicional en mesas: mecanismo para incorporar a la tabla de mesas todos los campos jerárquicos disponibles (partido Judicial, Comarca, Diputación Provincial)

### ISSUE THREAD

**Issue by calba** [cesaralba/electResultSpainPython#3]
Así, de memoria, la jerarquía es:
- mesa
- sección
- distrito municipal
- municipio 
- partido judicial y/o comarca (¿qué se usa y en qué orden?)
- distrito electoral
- provincia
- comunidad autónoma
- total nacional

**Comment by cesaralba** [comment]
Solucionado con PR #4
